{"componentChunkName":"component---src-templates-post-template-js","path":"/note-how-to-troubleshoot-01","result":{"data":{"markdownRemark":{"id":"43e6189c-aae3-59a8-8c16-936fdbb207d3","html":"<h2 id=\"はじめに\" style=\"position:relative;\"><a href=\"#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB\" aria-label=\"はじめに permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>はじめに</h2>\n<p>PythonのWEBアプリケーションフレームワークを使っていたところ、次のようなエラーが発生しました。</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">エラーの内容： \ndjango.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n\nERRORS:\nauth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.\n        HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.\nauth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.\n        HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.\nmocrat_user.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.\n        HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.\nmocrat_user.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.\n        HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.\n\nSystem check identified 4 issues (0 silenced).</code></pre></div>\n<p>結論としては非常に初歩的な内容で、カスタムユーザを設定していたのにSettingsにAUTH_USER_MODELを設定し忘れていたよ、って話でした。</p>\n<p>ちなみに解消方法は、Settings.pyに以下の一文を追記するだけです。</p>\n<p><code class=\"language-text\">AUTH_USER_MODEL = 'AppName.ClassName'</code></p>\n<p>ところで、このエラーはトラブルシューティングの初歩について説明する上でちょうどいいサンプルでしたので、本記事ではこの事例を利用してトラブルシューティングの基本的なやり方について解説していきます。</p>\n<p>エラーが発生した場合の初歩的なググり方や考え方についてまとめます。</p>\n<h2 id=\"まずはエラー文を読む\" style=\"position:relative;\"><a href=\"#%E3%81%BE%E3%81%9A%E3%81%AF%E3%82%A8%E3%83%A9%E3%83%BC%E6%96%87%E3%82%92%E8%AA%AD%E3%82%80\" aria-label=\"まずはエラー文を読む permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>まずはエラー文を読む</h2>\n<p>さて、トラブルシューティングの初歩ですが、<strong>まずは嫌がらずにエラー文を読みましょう。</strong></p>\n<p>コンパイラやインタプリタは非常に賢いので、<strong>ちょっとした問題であれば、エラー文を読むだけで解消するケースが多い</strong>です。<br>\n例えば、Pythonの文法エラーの場合、次のような出力が確認できます。</p>\n<div class=\"gatsby-highlight\" data-language=\"python\"><pre class=\"language-python\"><code class=\"language-python\"><span class=\"token keyword\">print</span><span class=\"token punctuation\">(</span><span class=\"token number\">100</span> <span class=\"token operator\">+</span> <span class=\"token string\">\"Hello\"</span><span class=\"token punctuation\">)</span>\n\nTraceback <span class=\"token punctuation\">(</span>most recent call last<span class=\"token punctuation\">)</span><span class=\"token punctuation\">:</span>\nFile <span class=\"token string\">\"stdin\"</span><span class=\"token punctuation\">,</span> line <span class=\"token number\">1</span><span class=\"token punctuation\">,</span> <span class=\"token keyword\">in</span> module\nTypeError<span class=\"token punctuation\">:</span> unsupported operand <span class=\"token builtin\">type</span><span class=\"token punctuation\">(</span>s<span class=\"token punctuation\">)</span> <span class=\"token keyword\">for</span> <span class=\"token operator\">+</span><span class=\"token punctuation\">:</span> <span class=\"token string\">'int'</span> <span class=\"token keyword\">and</span> <span class=\"token string\">'str'</span></code></pre></div>\n<p>まず、Tracebackの直下に、エラーの原因となった場所が示されていますね。<br>\nこの例の場合は、1行目に問題があるようです。</p>\n<p>次に、エラーの理由が書かれています。</p>\n<p><code class=\"language-text\">TypeError: unsupported operand type(s) for +: 'int' and 'str'</code><br>\nとあるので、どうやらint型とstr型の加算はサポートされていないとのことです。</p>\n<p>この例の場合であれば、これを読めば100をクオテーションで囲い忘れていたことがエラーの原因だということがわかりましたね。</p>\n<h2 id=\"エラー文でググる\" style=\"position:relative;\"><a href=\"#%E3%82%A8%E3%83%A9%E3%83%BC%E6%96%87%E3%81%A7%E3%82%B0%E3%82%B0%E3%82%8B\" aria-label=\"エラー文でググる permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>エラー文でググる</h2>\n<p>では、冒頭で引用したエラー文をもう一度見てみます。</p>\n<p>色々書いてありますが、<strong>エラーの原因となるファイルの名前や行数については書いてありません。</strong></p>\n<p>また、<strong>原因に関連しそうな記載として、SystemCheckError: System check identified some issues とあります</strong>が、なんのことかよくわかりません。</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">エラーの内容：\n\ndjango.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n\nERRORS:\nauth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.\n        HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.\nauth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.\n        HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.\nmocrat_user.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.\n        HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.\nmocrat_user.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.\n        HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.\n\nSystem check identified 4 issues (0 silenced).</code></pre></div>\n<p>そんな時は、<strong>エラー文をコピペしてググってあげましょう。</strong></p>\n<p>その場合は、<strong>全文コピペすると上手く検索できないので、1文くらいに絞って検索</strong>します。</p>\n<p>また、その際、<strong>自作のファイル名などが入っていない部分を使用する</strong>ようにしましょう。</p>\n<p>今回のケースでは、“mocrat_user”というのが自作のファイル名なので、その部分は検索に含めないようにします。<br>\nこれは、自作のファイル名が検索ワードに含まれていると、それがノイズになって、期待する検索結果が得られない場合があるためです。</p>\n<p>では検索をしていきます。  </p>\n<p>まず、<code class=\"language-text\">SystemCheckError: System check identified some issues</code>でググってみました。</p>\n<p>まずは上位3記事を開いてみましょう。</p>\n<p>すると、内容が見事にバラバラでした。</p>\n<p>1記事目は、MEDIA_URLの設定に失敗してSystemCheckErrorが出力されており、2記事目はadmin.pyの設定漏れ、最後はmigrationの仕組みについての記事でした。</p>\n<p>ここから考えられることとして、<strong>どうやらSystemCheckErrorは特定の事象ではなく、エラーに対して汎用的に用いられる出力ということが予想</strong>できます。</p>\n<h2 id=\"原因を絞り込んでググる\" style=\"position:relative;\"><a href=\"#%E5%8E%9F%E5%9B%A0%E3%82%92%E7%B5%9E%E3%82%8A%E8%BE%BC%E3%82%93%E3%81%A7%E3%82%B0%E3%82%B0%E3%82%8B\" aria-label=\"原因を絞り込んでググる permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>原因を絞り込んでググる</h2>\n<p>前項で、SystemCheckErrorはどうやら様々な事象に対して出力されるものであることがわかりました。</p>\n<p>そのため、<strong>検索ワードを変えたいのですが、その前にまず問題の原因を絞り込む作業</strong>をしていきます。<br>\n今回の場合は、エラー文にファイル名が出力されていないことや、SystemCheckErrorを検索した結果より、設定ファイルや権限のミスが原因かなという予想をすることができます。</p>\n<p>また、エラーの詳細の記載より、Userモデルに関する問題の可能性が高そうに見えます。<br>\n具体的には、Reverse accessor に関する記載がありました。</p>\n<p>ここで、<code class=\"language-text\">Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.</code>の一文で検索をかけてみましょう。</p>\n<p>今度は、上位すべてに同じ問題に関する記事が表示されました。<br>\nかなり確度が高そうです。</p>\n<p>結果としてはこちらが正解で、カスタムユーザを定義しているにも関わらず、<code class=\"language-text\">AUTH_USER_MODEL</code>を記載していなかったために、モデルが衝突していたようです。</p>\n<h2 id=\"エラーコードでググる\" style=\"position:relative;\"><a href=\"#%E3%82%A8%E3%83%A9%E3%83%BC%E3%82%B3%E3%83%BC%E3%83%89%E3%81%A7%E3%82%B0%E3%82%B0%E3%82%8B\" aria-label=\"エラーコードでググる permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>エラーコードでググる</h2>\n<p>さて、今回はエラー文の内容を検索することで上手く解決方法が見つかりましたが、そのほかのテクニックとして<strong>エラーコードでググる</strong>という方法もあります。</p>\n<p>特に、<strong>マイナーなシステムを使っていると、エラー文で検索しても思うように情報がヒットしない場合</strong>があります。<br>\nそんな時は、<strong>表示されているエラーコードで検索をしてみると、公式のドキュメントなどから原因に関連する情報が取得できる</strong>場合があるので、ぜひ試してみてください。</p>\n<p>今回のケースでは、<code class=\"language-text\">fields.E304</code>というエラーコードが表示されています。</p>\n<p>そのため、“Django fields.E304”という検索ワードでも、この問題の原因と解決方法に関するページがヒットしました。</p>\n<h2 id=\"まとめ\" style=\"position:relative;\"><a href=\"#%E3%81%BE%E3%81%A8%E3%82%81\" aria-label=\"まとめ permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>まとめ</h2>\n<p>今回は、Djangoのトラブルシューティングを題材に、エラー文を読むことや、検索の方法など、初歩的なナレッジについてまとめました。</p>\n<p>トラブルシューティングのプロセスについては意外と情報が少なく、個人のセンス任せな部分が多い分野なのかなと感じています。</p>\n<p>今後も何かいい題材があれば、より詳細なトラブルシューティングのノウハウについて紹介していきますのでぜひご参照ください。</p>","fields":{"slug":"/note-how-to-troubleshoot-01","tagSlugs":["/tag/notes/"]},"frontmatter":{"date":"2020-07-05","description":"本記事ではこの事例を利用してトラブルシューティングの基本的なやり方について解説していきます。","tags":["Notes"],"title":"【トラブルシューティング入門 #1】エラー文でググる","socialImage":{"publicURL":"/static/dc4d8b7f8795f3c3d3489d9957d155f2/no-image.png"}}}},"pageContext":{"slug":"/note-how-to-troubleshoot-01"}},"staticQueryHashes":["251939775","401334301","825871152"]}